db:
  image: postgres

web:
  build: .
  ports:
    - '3000:3000'
  volumes:
    - '/Users/jpsilva/dev/rails/goe-rails:/var/app'
  command: rails s -b '0.0.0.0'
#  command: rake RAILS_ENV=development docker_tasks:migrate_and_start
  links:
    - db
